FROM dunglas/frankenphp:php8.3

WORKDIR /app

RUN install-php-extensions pdo_mysql

COPY . /app

ENV SERVER_ROOT=/app
ENV SERVER_NAME=http://

CMD ["frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile"]